### ISSUE TITLE
Inconsistency with paper

### ISSUE THREAD

**Issue by CookiePPP** [rishikksh20/Fre-GAN-pytorch#3]
https://arxiv.org/pdf/2106.02297.pdf

In section 2.3
"_After each level of DWT, all the frequency sub-bands are channel-wise concatenated and passed to convolutional layers_"

---

https://github.com/rishikksh20/Fre-GAN-pytorch/blob/91d0e4678199003f6b32d53c7501e6123fb70fc5/discriminator.py#L242-L246

You are concatenating on the length dim resulting in an odd looking tensor where the first half is audio features and the 2nd half is DWT features, and local waveform/DWT information can't mix properly.

Is there any reason for this? I feel very confused looking at this, but you've done it twice so I assume there's some reason for this.

**Comment by leminhnguyen** [comment]
Hey @CookiePPP, For my understanding the sentence _"After each level of DWT, all the frequency sub-bands are channel-wise concatenated and passed to convolutional layers"_ should refer to the lines:

https://github.com/rishikksh20/Fre-GAN-pytorch/blob/91d0e4678199003f6b32d53c7501e6123fb70fc5/discriminator.py#L228-L235

**Comment by CookiePPP** [comment]
@leminhnguyen
Thanks!
Yes I see. I wonder if "and passed to convolutional layers" would have meant channel-wise concat or length wise. 🤔 

I suppose the difference shouldn't be large in terms of quality, just maybe an increase in compute/training time from having the discriminator latents get longer after every layer.
